export * as eventalerts from './eventalerts/index';
export * as orgTools from './orgTools/index';
export * as serviceControlPolicy from './scp/index';
export * as remailer from './remailer/index';
export * as enterpriseSupport from './enterprisesupport/index';
export * as sso from './sso/index';
export * as helpers from './helpers/index';
export * as organizations from './aws_organizations/index';
export * as transfer from './transfer/index';